# Docker Swarm Stack f√ºr OwnCloud
# Deploy mit: docker stack deploy -c docker-stack.yml storage

version: '3.8'

services:
  mysql:
    image: mariadb:latest
    networks:
      - proxy
    env_file: mysql.env
    volumes:
      - owncloud-sql:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: always

  owncloud:
    image: owncloud/server:latest
    volumes:
      - owncloud-html:/var/www/html
      - owncloud-data:/mnt/data
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      - proxy
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.owncloud.entrypoints=web"
      - "traefik.http.routers.owncloud.rule=Host(`owncloud.${DOMAIN}`)"
      - "traefik.http.routers.owncloud.middlewares=redirect-to-https@docker"
      - "traefik.http.routers.owncloud-secure.entrypoints=websecure"
      - "traefik.http.routers.owncloud-secure.rule=Host(`owncloud.${DOMAIN}`)"
      - "traefik.http.routers.owncloud-secure.tls=true"
      - "traefik.http.routers.owncloud-secure.tls.certresolver=http_resolver"
      - "traefik.http.services.owncloud.loadbalancer.server.port=80"
      - "traefik.http.routers.owncloud-secure.middlewares=default@file,admin-whitelist@file,rate-limit@docker"
      - "traefik.http.services.owncloud.loadbalancer.sticky.cookie.httpOnly=true"
      - "traefik.http.services.owncloud.loadbalancer.sticky.cookie.secure=true"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: always

networks:
  proxy:
    external: true

volumes:
  owncloud-html:
    driver: local
  owncloud-data:
    driver: local
  owncloud-sql:
    driver: local

